/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/App`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/componenets/grid/HexGrid`; params?: Router.UnknownInputParams; } | { pathname: `/componenets/grid/HexTile`; params?: Router.UnknownInputParams; } | { pathname: `/componenets/hud/ScoreBoard`; params?: Router.UnknownInputParams; } | { pathname: `/componenets/overlays/GameOverModal`; params?: Router.UnknownInputParams; } | { pathname: `/componenets/overlays/StartOverlay`; params?: Router.UnknownInputParams; } | { pathname: `/constants/game`; params?: Router.UnknownInputParams; } | { pathname: `/styles/appStyles`; params?: Router.UnknownInputParams; } | { pathname: `/types/game`; params?: Router.UnknownInputParams; } | { pathname: `/utils/grid`; params?: Router.UnknownInputParams; } | { pathname: `/utils/highScore`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/App`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/componenets/grid/HexGrid`; params?: Router.UnknownOutputParams; } | { pathname: `/componenets/grid/HexTile`; params?: Router.UnknownOutputParams; } | { pathname: `/componenets/hud/ScoreBoard`; params?: Router.UnknownOutputParams; } | { pathname: `/componenets/overlays/GameOverModal`; params?: Router.UnknownOutputParams; } | { pathname: `/componenets/overlays/StartOverlay`; params?: Router.UnknownOutputParams; } | { pathname: `/constants/game`; params?: Router.UnknownOutputParams; } | { pathname: `/styles/appStyles`; params?: Router.UnknownOutputParams; } | { pathname: `/types/game`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/grid`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/highScore`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/App${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/componenets/grid/HexGrid${`?${string}` | `#${string}` | ''}` | `/componenets/grid/HexTile${`?${string}` | `#${string}` | ''}` | `/componenets/hud/ScoreBoard${`?${string}` | `#${string}` | ''}` | `/componenets/overlays/GameOverModal${`?${string}` | `#${string}` | ''}` | `/componenets/overlays/StartOverlay${`?${string}` | `#${string}` | ''}` | `/constants/game${`?${string}` | `#${string}` | ''}` | `/styles/appStyles${`?${string}` | `#${string}` | ''}` | `/types/game${`?${string}` | `#${string}` | ''}` | `/utils/grid${`?${string}` | `#${string}` | ''}` | `/utils/highScore${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/App`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/componenets/grid/HexGrid`; params?: Router.UnknownInputParams; } | { pathname: `/componenets/grid/HexTile`; params?: Router.UnknownInputParams; } | { pathname: `/componenets/hud/ScoreBoard`; params?: Router.UnknownInputParams; } | { pathname: `/componenets/overlays/GameOverModal`; params?: Router.UnknownInputParams; } | { pathname: `/componenets/overlays/StartOverlay`; params?: Router.UnknownInputParams; } | { pathname: `/constants/game`; params?: Router.UnknownInputParams; } | { pathname: `/styles/appStyles`; params?: Router.UnknownInputParams; } | { pathname: `/types/game`; params?: Router.UnknownInputParams; } | { pathname: `/utils/grid`; params?: Router.UnknownInputParams; } | { pathname: `/utils/highScore`; params?: Router.UnknownInputParams; };
    }
  }
}
